# Generated by Django 2.0.7 on 2018-07-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_position', models.CharField(max_length=100, verbose_name='Officer Posistion')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=300, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
            ],
        ),
    ]
