# Generated by Django 2.0.7 on 2018-07-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
