# Generated by Django 2.0.7 on 2018-08-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0003_dues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dues',
            options={'verbose_name': 'Dues Announcement'},
        ),
        migrations.AddField(
            model_name='dues',
            name='title',
            field=models.CharField(default='First', max_length=30),
            preserve_default=False,
        ),
    ]
