# Generated by Django 2.0.7 on 2018-08-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0004_auto_20180803_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dues',
            name='announcement',
            field=models.CharField(max_length=50),
        ),
    ]
