# Generated by Django 2.0.7 on 2018-07-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Body',
            new_name='Announcement_Body',
        ),
        migrations.RenameModel(
            old_name='Title',
            new_name='Announcement_Title',
        ),
    ]
