# Generated by Django 2.0.7 on 2018-08-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='pub_date',
            field=models.DateTimeField(help_text="Click 'Today' and 'Now'", verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title_text',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
