# Generated by Django 2.0.7 on 2018-07-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180715_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body_text', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Announcement',
            },
        ),
        migrations.RemoveField(
            model_name='announcement_body',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Announcement_Body',
        ),
        migrations.DeleteModel(
            name='Announcement_Title',
        ),
    ]
