# Generated by Django 2.0.7 on 2018-08-05 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180804_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date'),
            preserve_default=False,
        ),
    ]
