# Generated by Django 2.0.7 on 2018-08-19 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180806_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Calendar Event'},
        ),
    ]
