# Generated by Django 2.0.7 on 2018-08-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(help_text='Pick the date with the calendar icon')),
                ('start_time', models.TimeField(help_text='Use military time i.e. 3p.m. is 15:00')),
                ('end_time', models.TimeField(help_text='Use military time i.e. 6p.m. is 18:00')),
                ('location', models.CharField(max_length=200)),
                ('more_info', models.CharField(max_length=500)),
                ('website', models.URLField(blank=True, max_length=1000)),
                ('pub_date', models.DateTimeField(help_text="Click 'Today' and 'Now'", verbose_name='Publication date')),
            ],
        ),
    ]
