# Generated by Django 2.0.7 on 2018-08-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickralbums',
            name='link',
            field=models.URLField(help_text='Share Link to the Flickr album', max_length=1000),
        ),
        migrations.AlterField(
            model_name='flickralbums',
            name='name',
            field=models.CharField(help_text='Name of photo album', max_length=100),
        ),
    ]
