# Generated by Django 2.0.7 on 2018-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20180720_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='pictures/class_pictures'),
        ),
    ]
