# Generated by Django 2.0.7 on 2018-07-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20180721_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='pictures/static/pictures/class_pictures'),
        ),
    ]
