# Generated by Django 2.0.7 on 2018-07-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20180721_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
