# Generated by Django 2.0.7 on 2018-07-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
