# Generated by Django 2.0.7 on 2018-07-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pictures', '0007_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePhotosAlbums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=10000)),
            ],
        ),
    ]
