# Generated by Django 2.0.7 on 2018-07-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0008_googlephotosalbums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlephotosalbums',
            options={'verbose_name': 'Photo Album', 'verbose_name_plural': 'Photo Albums'},
        ),
    ]
