# Generated by Django 2.0.7 on 2018-07-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_auto_20180727_2132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GooglePhotosAlbums',
            new_name='FlickrAlbums',
        ),
    ]
